// RealExampleIntegrationTests/Optimization/JudgeSignature.cs
using DSpyNet.DSPy.Core;

namespace RealExampleIntegrationTests.Optimization
{
    [DspInstruction("You are an expert content editor and critic. You need to evaluate the quality of a generated Telegram post based on a raw news source.")]
    public class ContentJudgeSignature : IDSpySignature
    {
        [DspInput(Prefix = "Raw News:", Description = "The original news source text.")]
        public string Input { get; set; }

        [DspInput(Prefix = "Generated Post:", Description = "The post generated by the AI.")]
        public string Output { get; set; }

        [DspInput(Prefix = "Reference Style:", Description = "An example of a perfect post (optional context).")]
        public string Reference { get; set; }

        [DspOutput(Prefix = "Score:", Description = "A score from 1 to 5, where 1 is terrible and 5 is perfect style match and accuracy. Output ONLY the number.")]
        public string Score { get; set; }

        [DspOutput(Prefix = "Reasoning:", Description = "Brief explanation of the score.")]
        public string Reasoning { get; set; }
    }
}